
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALPHA ELEMENTS ELEMMH NAME NL SIZE SIZE_ZERO UNKNOWNaddress : ALPHA NAME SIZE SIZE_ZERO ELEMMH ELEMENTSerr : UNKNOWNaddress : err NLaddress : ALPHA err NLaddress : ALPHA NAME err NLaddress : ALPHA NAME SIZE err NLaddress : ALPHA NAME SIZE SIZE_ZERO err NLaddress : ALPHA NAME SIZE SIZE_ZERO ELEMMH err NLaddress : ALPHA NAME SIZE SIZE_ZERO ELEMMH ELEMENTS err NL'
    
_lr_action_items = {'SIZE_ZERO':([9,],[12,]),'ELEMENTS':([15,],[18,]),'NL':([1,2,7,8,13,14,19,20,],[5,-2,10,11,16,17,21,22,]),'NAME':([4,],[6,]),'UNKNOWN':([0,4,6,9,12,15,18,],[2,2,2,2,2,2,2,]),'ELEMMH':([12,],[15,]),'ALPHA':([0,],[4,]),'SIZE':([6,],[9,]),'$end':([3,5,10,11,16,17,18,21,22,],[0,-3,-4,-5,-6,-7,-1,-8,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'err':([0,4,6,9,12,15,18,],[1,7,8,13,14,19,20,]),'address':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> address","S'",1,None,None,None),
  ('address -> ALPHA NAME SIZE SIZE_ZERO ELEMMH ELEMENTS','address',6,'p_address','PLY_Parcer.py',30),
  ('err -> UNKNOWN','err',1,'p_err','PLY_Parcer.py',39),
  ('address -> err NL','address',2,'p_address_zero_err_type','PLY_Parcer.py',46),
  ('address -> ALPHA err NL','address',3,'p_address_first_err_type','PLY_Parcer.py',50),
  ('address -> ALPHA NAME err NL','address',4,'p_address_second_err_type','PLY_Parcer.py',54),
  ('address -> ALPHA NAME SIZE err NL','address',5,'p_address_third_err_type','PLY_Parcer.py',58),
  ('address -> ALPHA NAME SIZE SIZE_ZERO err NL','address',6,'p_address_fourth_err_type','PLY_Parcer.py',62),
  ('address -> ALPHA NAME SIZE SIZE_ZERO ELEMMH err NL','address',7,'p_address_fifth_err_type','PLY_Parcer.py',66),
  ('address -> ALPHA NAME SIZE SIZE_ZERO ELEMMH ELEMENTS err NL','address',8,'p_address_sixth_err_type','PLY_Parcer.py',70),
]
